#ifndef  MEM_MGR_H
#define  MEM_MGR_H

#define FLASH_SIZE			0x100000

#define APP_FILE_INFO_ADDR 		0
#define APP_FILE_INFO_SIZE      0x1000

#define APP_FILE_ADDR			(APP_FILE_INFO_ADDR + APP_FILE_INFO_SIZE)
#define APP_FILE_SIZE			0x40000


#define SENSOR_DATA_INFO_ADDR	    0x80000
#define SENSOR_DATA_INFO_SIZE	    0xF00     //0x80000  MAX 25Q80

#define SENSOR_DATA_ADDR		(SENSOR_DATA_INFO_ADDR + SENSOR_DATA_INFO_SIZE)
#define SENSOR_DATA_SIZE		(FLASH_SIZE-SENSOR_DATA_ADDR)


#endif

